### ISSUE TITLE
metaqa/schema.json is missing

### ISSUE THREAD

**Issue by AriKing11** [amazon-science/BYOKG-NAACL24#21]
when running ./src/explorer.py, will encounter an error as follows: 
"line 91, in read_triples
    with open(schema_fpath, 'r') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'data/metaqa/schema.json'"

**Comment by dhdhagar** [comment]
Hi @AriKing11, you need to first download the datasets using the instructions in the README: https://github.com/amazon-science/BYOKG-NAACL24?tab=readme-ov-file#download-datasets-and-graphs.
